- name: Install netaddr pip package on Ansible host (if this fails, you must manually install netaddr on your host)
  become: False
  pip:
    name: netaddr
  delegate_to: localhost

- name: copy aeon-ztps conf file
  template: src=aeonztp.conf dest=/etc/aeonztp.conf owner=root group=root mode=644

- name: copy aeon-ztps directories over
  copy: src="{{ TopDir }}/{{ item }}" dest={{ Install_dir }}
        owner={{ Aeon_user }} group={{ Aeon_group }}
        directory_mode=775
  with_items:
    - bin
    - etc
    - vendor_images
    - downloads
    - packages
    - docs

- name: copy aeon-ztp source files over
  copy:
    src: "{{ TopDir }}/{{ item }}"
    dest: "{{ Install_dir }}/src"
    owner: "{{ Aeon_user }}"
    group: "{{ Aeon_group }}"
    directory_mode: 775
  with_items:
    - aeon_ztp
    - setup.py
    - MANIFEST.in
    - requirements.txt

- name: make bin items executable
  shell: chmod +x {{ Install_dir }}/bin/*

- name: make directories group writable
  command: chmod -R g+w {{ Install_dir }}/{{ item }}
  with_items:
    - vendor_images
    - downloads
    - docs

- name: create aeonztp directories
  file: path={{ Install_dir }}/{{ item }} state=directory
        owner={{ Aeon_user }} group={{ Aeon_group }} mode=755
  with_items:
    - logs
    - run

- name: create aeonztp /var directories
  file: path={{ item }} state=directory
        owner={{ Aeon_user }} group={{ Aeon_group }} mode=755
  with_items:
    - /var/log/aeon-ztp
    - /var/run/aeon-ztp

- name: copy ztp-scripts to tftpboot
  copy: src="{{ TopDir }}/ztp-scripts/" dest={{ Install_dir }}/tftpboot
        owner=nobody mode=777

- name: symlink ztp-cumulus in downloads directory
  file: state=link
        src={{ Install_dir }}/tftpboot/ztp-cumulus.sh
        dest={{ Install_dir }}/downloads/ztp-cumulus.sh

- name: symlink ztp-cros in downloads directory
  file: state=link
        src={{ Install_dir }}/tftpboot/ztp-cros.sh
        dest={{ Install_dir }}/downloads/ztp-cros.sh


- name: install aztp-db-flush utility
  file: state=link src={{ Install_dir }}/bin/aztp-db-flush
        dest=/usr/local/bin/aztp-db-flush

- name: Build aeon-ztp from source
  shell: python setup.py sdist
  args:
    chdir: "{{ Install_dir }}/src"

- find: paths="{{ Install_dir }}/src/dist" patterns="aeon-ztp*"
  register: search_results

- name: Install aeon-ztp from local package
  pip:
    name: "{{ search_results.files[0].path }}"

- name: Move aeon-ztps package install file to packages directory
  shell: "mv {{ search_results.files[0].path }} {{ Install_dir }}/packages/"

- name: TEMPORARY - Install aeon-venos from local package
  pip:
    name: "{{ Install_dir }}/packages/aeon-venos-0.2.0.tar.gz"

# build the docs
#
#- name: Build docs using Sphinx
#  shell: make html
#  args:
#    chdir: "/opt/aeonztps/docs"

- name: Remove aeon-ztp source directory
  file:
    path: "{{ Install_dir }}/src"
    state: absent

- name: sudoers for aeon ZTP helper scripts
  copy: src=aeon-ztp.conf dest=/etc/sudoers.d mode=600
